### PR TITLE
Bump JSONL line length limit to 1MB (from 64k)

### PR DESCRIPTION
**Pull request by fritzgrabo**
Hi :wave:

At work, we wanted to run some queries against a 600MB `.jsonl` file with pretty long individual lines earlier today and ran into an issue reading the file:

```shell
$ dsq ~/sample.jsonl "SELECT COUNT(1) FROM {}"
bufio.Scanner: token too long
```

Turns out that `bufio.Scanner` only buffers up to 64k bytes when looking for the next token to split the input on.

In a gist, the scanner starts by buffering the first 4k bytes of the input, looking for the next token to split the input on (a newline character by default). If it can't find a token, it doubles the size of the buffer and tries again. It keeps doing that until it either hits a token or the maximum buffer size, which is 64k by default. Please see https://pkg.go.dev/bufio#pkg-constants and https://pkg.go.dev/bufio#Scanner.Buffer for details.

In this PR, I propose to bump the maximum size of the buffer up to 1M.

I don't think that this has an impact on resources/performance for files with shorter lines: the 1M is just a maximum, `bufio` doesn't pre-allocate any memory here.

To demonstrate the fix:

```shell
# The 1st line of the input file is barely within limits
$ head -1 ~/sample.jsonl | wc -c
   64317

# The 52nd line of the input file is > 64kb long
$ head -52 ~/sample.jsonl | tail -1 | wc -c
   66068

# As a result, `dsq` can't parse the file
$ dsq ~/sample.jsonl "SELECT COUNT(1) FROM {}"
bufio.Scanner: token too long

# With the proposed patch, `dsq` can parse the file alright
$ ./dsq ~/sample.jsonl "SELECT COUNT(1) FROM {}"
[{"COUNT(1)":9467}]
```

Please let me know what you think. Thanks!

### CODE REVIEW

**Comment by eatonphil** [comment]
This is great, thank you!

I have two requests:
1. Could you add a test with a large JSON line that would fail without this patch?
2. Could you make a new `newLargeScanner` function and have the other calls to NewScanner call it instead?

Here's a not-working diff to get you started on both:

```
$ git diff
diff --git a/runner/file.go b/runner/file.go
index 2f4aa1a..241aecb 100644
--- a/runner/file.go
+++ b/runner/file.go
@@ -437,10 +437,19 @@ func transformJSONConcatFile(in string, out io.Writer) error {
        return transformJSONConcat(r, out)
 }
 
+func newLargeLineScanner(in) {
+       scanner := bufio.NewScanner(in)
+
+       // Bump line length limit to 1MB (from 64k)
+       buf := make([]byte, 4096)
+       scanner.Buffer(buf, 1024 * 1024)
+       return scanner
+}
+
 func transformJSONLines(in io.Reader, out io.Writer) error {
        first := true
        return withJSONOutWriter(out, "[", "]", func() error {
-               scanner := bufio.NewScanner(in)
+               scanner := newLargeLineScanner(in)
                for scanner.Scan() {
                        if !first {
                                _, err := out.Write([]byte(",\n"))
@@ -477,7 +486,7 @@ var BUILTIN_REGEX = map[MimeType]*regexp.Regexp{
 }
 
 func transformRegexp(in io.Reader, out io.Writer, re *regexp.Regexp) error {
-       scanner := bufio.NewScanner(in)
+       scanner := newLargeLineScanner(in)
        return withJSONArrayOutWriterFile(out, func(w *jsonutil.StreamEncoder) error {
                row := map[string]any{}
                for scanner.Scan() {
diff --git a/runner/file_test.go b/runner/file_test.go
index 24ce693..41e3e47 100644
--- a/runner/file_test.go
+++ b/runner/file_test.go
@@ -14,36 +14,54 @@ import (
 )
 
 func Test_transformJSONLines(t *testing.T) {
-       tmp, err := ioutil.TempFile("", "")
-       defer os.Remove(tmp.Name())
-       assert.Nil(t, err)
+       longGeneratedJSONString := " fill me in "
+       tests := []struct{
+               input string
+               output []map[string]any
+       }{
+               {
+                       `{"a": 1, "b": 2}
+{"a": 2, "b": 3}`,
+                       []map[string]any{
+                               {
+                                       "a": float64(1),
+                                       "b": float64(2),
+                               },
+                               {
+                                       "a": float64(2),
+                                       "b": float64(3),
+                               },
+                       },
+               },
+               {
+                       longGeneratedJsonString,
+                       longGeneratedJsonStringRepr,
+               },
+       }
 
-       tmp.WriteString(`{"a": 1, "b": 2}
-{"a": 2, "b": 3}`)
+       for _, test := range tests {
+               tmp, err := ioutil.TempFile("", "")
+               assert.Nil(t, err)
 
-       tmp2, err := ioutil.TempFile("", "")
-       defer os.Remove(tmp2.Name())
-       assert.Nil(t, err)
+               tmp.WriteString(test.input)
 
-       err = transformJSONLinesFile(tmp.Name(), tmp2)
-       assert.Nil(t, err)
+               tmp2, err := ioutil.TempFile("", "")
+               assert.Nil(t, err)
 
-       var m []map[string]any
-       tmp2Bs, err := ioutil.ReadFile(tmp2.Name())
-       assert.Nil(t, err)
-       err = json.Unmarshal(tmp2Bs, &m)
-       assert.Nil(t, err)
+               err = transformJSONLinesFile(tmp.Name(), tmp2)
+               assert.Nil(t, err)
 
-       assert.Equal(t, []map[string]any{
-               {
-                       "a": float64(1),
-                       "b": float64(2),
-               },
-               {
-                       "a": float64(2),
-                       "b": float64(3),
-               },
-       }, m)
+               var m []map[string]any
+               tmp2Bs, err := ioutil.ReadFile(tmp2.Name())
+               assert.Nil(t, err)
+               err = json.Unmarshal(tmp2Bs, &m)
+               assert.Nil(t, err)
+
+               assert.Equal(t, test.output, m)
+
+               os.Remove(tmp.Name())
+               os.Remove(tmp2.Name())
+       }
 }
 
 func Test_parquet(t *testing.T) {
```

**Comment by eatonphil** [comment]
Also, tests are failing because you need to run gofmt. `cd runner && gofmt -w -s .` should fix it.

**Comment by fritzgrabo** [comment]
That's great feedback, thank you!

I've updated `file.go` and the related tests according to your suggestions.

For reference: without this patch in place, the new test fails with this:

```
--- FAIL: Test_transformJSONLines (0.01s)
    file_test.go:58: 
        	Error Trace:	file_test.go:58
        	Error:      	Expected nil, but got: &errors.errorString{s:"bufio.Scanner: token too long"}
        	Test:       	Test_transformJSONLines
    file_test.go:64: 
        	Error Trace:	file_test.go:64
        	Error:      	Expected nil, but got: &json.SyntaxError{msg:"unexpected end of JSON input", Offset:1}
        	Test:       	Test_transformJSONLines
    file_test.go:66: 
        	Error Trace:	file_test.go:66
        	Error:      	Not equal: 
        	            	expected: []map[string]interface {}{map[string]interface {}{"a":1, "b":"Omnis ut ut voluptatem provident eaque necessitatibus quia. ...
```

With the patch in place, it passes 🎉

**Comment by eatonphil** [comment]
Looks good! Will merge when passing. Thank you!

**Review by eatonphil — APPROVED** [review]

**Comment by eatonphil** [comment]
You're set!

**Pull request merged**
