### PR TITLE
Fix the data error when loading json with path

### LINKED ISSUE #91: Excel sheet2 also show sheet1 data, not only sheet2
- OS: almalinux 9
- Shell: bash
 - dsq version: v0.22.0

```
$ dsq --pretty test-data.xlsx 'SELECT * FROM {"Sheet2"}'
+---+---+---+ 
| A | B | C |                                                                                                                                     
+---+---+---+                                                                                                                                     
|   | 1 | 2 |                                                                                                                                     
|   | 3 | 4 |                                                                                                                                     
+---+---+---+                                                                                                                                     
(2 rows)                                                                                                                                          
```

Excel test data as follows: [test-data.xlsx](https://github.com/multiprocessio/dsq/files/9457846/test-data.xlsx)

### PR DESCRIPTION
**Pull request by xwjdsh**
Fix https://github.com/multiprocessio/dsq/issues/91, https://github.com/multiprocessio/dsq/issues/96

### CODE REVIEW

**Comment by eatonphil** [comment]
Awesome! I was dreading dealing with this. This seems like a good fix for now.

**Comment by eatonphil** [comment]
Tests in both would be great. Tests here help show the issue earlier. We can just add a basic one to dsq when you update the go.mod there after this is merged.

**Comment by xwjdsh** [comment]
Sorry for being late, I added a test case, and after this is merged, I will add a test case of the excel file to dsq.

**Comment by eatonphil** [comment]
No problem! Take your time!

**Comment by xwjdsh** [comment]
Oh, the CI failed. It looks like a config issue, I have no idea how to fix it.
```
"Unable to retrieve Sheets client: unexpected end of JSON input"
```

**Comment by eatonphil** [comment]
Those tests fail unless it's run by someone in the Github multiprocessio org. They are expected for most contributors to fail.

Thanks for the fix!

**Pull request merged**
